### ISSUE TITLE
Нет возможности использовать UniqueConstraint вместо unique_together

### ISSUE THREAD

**Issue by NikulinAnton** [pikhovkin/django-soft-remover#2]
Добавить возможности использовать UniqueConstraint вместо unique_together
"Use UniqueConstraint with the constraints option instead. UniqueConstraint provides more functionality than unique_together. unique_together may be deprecated in the future" согласно [документации Django](https://docs.djangoproject.com/en/4.1/ref/models/options/#unique-together)

Пример
```python
class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'remver'], name='unique_together_name_remver')
        ]
```

**Comment by pikhovkin** [comment]
done
